export function createDefaultState(now = Date.now()) {
  return {
    siteSections: [
      {
        id: "feed",
        name: "Поле",
        kind: "social",
      },
      {
        id: "top",
        name: "Пульс",
        kind: "leaderboard",
      },
    ],
    users: [
      {
        id: "guest",
        name: "Гость",
        handle: "@guest",
        bio: "Пишет без привязки к Discord.",
        joinedAt: now,
        timeOnSiteMinutes: 0,
      },
      {
        id: "rub1kub",
        name: "rub1kub",
        handle: "@rub1kub",
        bio: "Ведёт свою доску и делится короткими заметками.",
        joinedAt: now - 1000 * 60 * 60 * 24 * 42,
        timeOnSiteMinutes: 420,
      },
      {
        id: "kotleta",
        name: "Котлета",
        handle: "@kotleta",
        bio: "Пишет короткие заметки.",
        joinedAt: now - 1000 * 60 * 60 * 24 * 30,
        timeOnSiteMinutes: 260,
      },
      {
        id: "navi",
        name: "Нави",
        handle: "@navi",
        bio: "Тестирует идеи и интерфейс.",
        joinedAt: now - 1000 * 60 * 60 * 24 * 18,
        timeOnSiteMinutes: 185,
      },
    ],
    activeUserId: "guest",
    walls: [
      {
        id: "main",
        siteSectionId: "feed",
        name: "Общая",
        ownerId: "rub1kub",
        description: "Общая доска для коротких заметок и быстрых обсуждений.",
        rules: "Без спама и личных данных.",
        publishMode: "open",
      },
      {
        id: "notes",
        siteSectionId: "feed",
        name: "Заметки",
        ownerId: "rub1kub",
        description: "Тихие записи, мысли и заметки.",
        rules: "Пиши по делу.",
        publishMode: "open",
      },
      {
        id: "space:minecraft",
        siteSectionId: "space",
        name: "Модпак CyberKotleta",
        ownerId: "rub1kub",
        description: "мод пак для игры на WhiteShield",
        rules: "",
        accentColor: "green",
        publishMode: "owner",
      },
    ],
    utilityPositions: {
      "minecraft:download-card": {
        x: 274,
        y: 44,
      },
    },
    posts: [
      {
        id: "minecraft-download-post",
        wallId: "space:minecraft",
        authorId: "rub1kub",
        text: "мод пак для игры на WhiteShield",
        attachments: [],
        reactions: 0,
        views: {
          total: 0,
          uniqueUserIds: [],
        },
        position: {
          x: 274,
          y: 44,
        },
        createdAt: now - 1000 * 60,
      },
    ],
    comments: [],
    postConnections: [],
    follows: [
      {
        id: "follow-1",
        targetId: "kotleta",
        targetType: "user",
        createdAt: now - 1000 * 60 * 60 * 5,
      },
      {
        id: "follow-2",
        targetId: "main",
        targetType: "wall",
        createdAt: now - 1000 * 60 * 60 * 3,
      },
    ],
    savedPostIds: [],
    pinnedPostIds: [],
    hiddenPostIds: [],
    hiddenCommentIds: [],
    notifications: [],
    pixelCells: [],
    pixelCooldowns: {},
    reports: [],
  };
}
